<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-semibold uppercase text-emerald-700">{{ __('Credit Operations') }}</p><h2 class="mt-1 text-2xl font-semibold text-slate-950">{{ __('New Loan Application') }}</h2></div></x-slot>
    <div class="mx-auto max-w-3xl px-4 py-8 sm:px-6 lg:px-8">
        @if ($errors->any())<div class="mb-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        @if ($loanTypes->isEmpty())<div class="rounded-lg border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{{ __('Create an active loan type before accepting applications.') }} <a href="{{ route('loan-types.create') }}" class="font-semibold underline">{{ __('Create loan type') }}</a></div>
        @elseif ($customers->isEmpty())<div class="rounded-lg border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900">{{ __('A customer with an open account is required before creating a loan application.') }} <a href="{{ route('accounts.create') }}" class="font-semibold underline">{{ __('Open an account') }}</a></div>
        @else
            <form method="POST" action="{{ route('loans.store') }}" class="space-y-6 rounded-lg border border-slate-200 bg-white p-6 shadow-sm">@csrf
                <div><x-input-label for="customer_id" :value="__('Customer')" /><select id="customer_id" name="customer_id" class="mt-1 block w-full rounded-lg border-slate-300 bg-white shadow-sm focus:border-emerald-500 focus:ring-emerald-500" required><option value="">{{ __('Select customer') }}</option>@foreach ($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id') == $customer->id)>{{ $customer->full_name }} - {{ $customer->customer_number }}</option>@endforeach</select><x-input-error :messages="$errors->get('customer_id')" class="mt-2" /></div>
                <div><x-input-label for="account_id" :value="__('Repayment / Disbursement Account')" /><select id="account_id" name="account_id" class="mt-1 block w-full rounded-lg border-slate-300 bg-white shadow-sm focus:border-emerald-500 focus:ring-emerald-500" required><option value="">{{ __('Select open account') }}</option>@foreach ($customers as $customer)@foreach ($customer->accounts as $account)<option value="{{ $account->id }}" @selected(old('account_id') == $account->id)>{{ $customer->full_name }} - {{ $account->account_number }} ({{ $account->accountType?->currency }})</option>@endforeach @endforeach</select><p class="mt-1 text-xs text-slate-500">{{ __('The same open account receives disbursement and can be used for account-debit payments.') }}</p><x-input-error :messages="$errors->get('account_id')" class="mt-2" /></div>
                <div><x-input-label for="loan_type_id" :value="__('Loan Type')" /><select id="loan_type_id" name="loan_type_id" class="mt-1 block w-full rounded-lg border-slate-300 bg-white shadow-sm focus:border-emerald-500 focus:ring-emerald-500" required><option value="">{{ __('Select loan type') }}</option>@foreach ($loanTypes as $loanType)<option value="{{ $loanType->id }}" @selected(old('loan_type_id') == $loanType->id)>{{ $loanType->name }} - {{ $loanType->annual_interest_rate }}% {{ $loanType->interest_method->label() }} ({{ $loanType->currency }})</option>@endforeach</select><x-input-error :messages="$errors->get('loan_type_id')" class="mt-2" /></div>
                <div class="grid grid-cols-1 gap-5 sm:grid-cols-2"><div><x-input-label for="requested_amount" :value="__('Requested Amount')" /><x-text-input id="requested_amount" name="requested_amount" type="number" min="0.01" step="0.01" class="mt-1 block w-full" :value="old('requested_amount')" required /><x-input-error :messages="$errors->get('requested_amount')" class="mt-2" /></div><div><x-input-label for="term_months" :value="__('Term (months)')" /><x-text-input id="term_months" name="term_months" type="number" min="1" max="600" class="mt-1 block w-full" :value="old('term_months')" required /><x-input-error :messages="$errors->get('term_months')" class="mt-2" /></div></div>
                <div><x-input-label for="purpose" :value="__('Purpose')" /><textarea id="purpose" name="purpose" rows="4" class="mt-1 block w-full rounded-lg border-slate-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500">{{ old('purpose') }}</textarea><x-input-error :messages="$errors->get('purpose')" class="mt-2" /></div>
                <div class="flex items-center justify-end gap-3"><a href="{{ route('loans.index') }}" class="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">{{ __('Cancel') }}</a><button type="submit" class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">{{ __('Submit Application') }}</button></div>
            </form>
        @endif
    </div>
</x-app-layout>
