<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-semibold uppercase text-emerald-700">{{ __('Branch Operations') }}</p><h2 class="mt-1 font-mono text-2xl font-semibold text-slate-950">{{ $branch->code }}</h2></div><a href="{{ route('branches.index') }}" class="text-sm font-semibold text-slate-600 hover:text-emerald-700">{{ __('Back to Branches') }}</a></div></x-slot>
    @php $statusClass = match ($branch->status->value) { 'open' => 'bg-emerald-50 text-emerald-700 ring-emerald-200', default => 'bg-slate-100 text-slate-700 ring-slate-200' }; @endphp
    <div class="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
        @if (session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{{ session('status') }}</div>@endif
        @if ($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
        <div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <section class="rounded-lg bg-slate-950 p-6 text-white shadow-sm lg:col-span-2"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase text-emerald-300">{{ __('Branch Name') }}</p><p class="mt-3 text-4xl font-semibold">{{ $branch->name }}</p></div><span class="inline-flex rounded-full px-3 py-1 text-xs font-semibold ring-1 ring-inset {{ $statusClass }}">{{ $branch->status->label() }}</span></div><div class="mt-8 grid grid-cols-1 gap-4 border-t border-slate-800 pt-5 sm:grid-cols-2"><div><p class="text-xs uppercase text-slate-500">{{ __('Branch Code') }}</p><p class="mt-1 font-mono text-lg font-semibold">{{ $branch->code }}</p></div><div><p class="text-xs uppercase text-slate-500">{{ __('Address') }}</p><p class="mt-1 text-sm font-semibold">{{ $branch->address ?? __('Not set') }}</p></div></div></section>
            <section class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase text-slate-500">{{ __('Manager') }}</p><p class="mt-2 text-xl font-semibold text-slate-950">{{ $branch->manager?->name ?? __('Not assigned') }}</p><p class="mt-1 text-sm text-slate-500">{{ $branch->manager?->email }}</p></section>
        </div>
        <section class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h3 class="font-semibold text-slate-950">{{ __('Branch Details') }}</h3><dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-xs uppercase text-slate-500">{{ __('Phone') }}</dt><dd class="mt-1 font-medium text-slate-900">{{ $branch->phone ?? __('Not set') }}</dd></div><div><dt class="text-xs uppercase text-slate-500">{{ __('Email') }}</dt><dd class="mt-1 font-medium text-slate-900">{{ $branch->email ?? __('Not set') }}</dd></div><div><dt class="text-xs uppercase text-slate-500">{{ __('Opened At') }}</dt><dd class="mt-1 font-medium text-slate-900">{{ $branch->opened_at?->format('Y-m-d H:i') ?? __('Not set') }}</dd></div><div><dt class="text-xs uppercase text-slate-500">{{ __('Closed At') }}</dt><dd class="mt-1 font-medium text-slate-900">{{ $branch->closed_at?->format('Y-m-d H:i') ?? __('Not set') }}</dd></div></dl></section>
        <section class="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="font-semibold text-slate-950">{{ __('Branch Actions') }}</h3><p class="text-sm text-slate-500">{{ __('Operational state changes are recorded on this branch.') }}</p></div><div class="flex flex-wrap gap-3">
            @if ($branch->status->value === 'open')
                <form method="POST" action="{{ route('branches.close', $branch) }}">@csrf<button class="rounded-lg border border-red-200 px-4 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">{{ __('Close Branch') }}</button></form>
            @else
                <form method="POST" action="{{ route('branches.open', $branch) }}">@csrf<button class="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800">{{ __('Open Branch') }}</button></form>
            @endif
            <a href="{{ route('branches.edit', $branch) }}" class="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">{{ __('Edit Branch') }}</a>
        </div></div></section>
    </div>
</x-app-layout>
