@php
    $selectedStatus = old('status', $loanType?->status?->value ?? 'active');
    $selectedMethod = old('interest_method', $loanType?->interest_method?->value ?? 'reducing_balance');
    $selectedFrequency = old('repayment_frequency', $loanType?->repayment_frequency?->value ?? 'monthly');
@endphp

<div class="grid grid-cols-1 gap-5 md:grid-cols-2">
    <div><x-input-label for="code" :value="__('Code')" /><x-text-input id="code" name="code" type="text" maxlength="24" class="mt-1 block w-full uppercase" :value="old('code', $loanType?->code)" required /><x-input-error :messages="$errors->get('code')" class="mt-2" /></div>
    <div><x-input-label for="name" :value="__('Name')" /><x-text-input id="name" name="name" type="text" class="mt-1 block w-full" :value="old('name', $loanType?->name)" required /><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
    <div><x-input-label for="currency" :value="__('Currency')" /><x-text-input id="currency" name="currency" type="text" maxlength="3" class="mt-1 block w-full uppercase" :value="old('currency', $loanType?->currency ?? 'SYP')" required /><x-input-error :messages="$errors->get('currency')" class="mt-2" /></div>
    <div><x-input-label for="status" :value="__('Status')" /><select id="status" name="status" class="mt-1 block w-full rounded-lg border-slate-300 bg-white shadow-sm focus:border-emerald-500 focus:ring-emerald-500" required>@foreach ($statuses as $status)<option value="{{ $status->value }}" @selected($selectedStatus === $status->value)>{{ $status->label() }}</option>@endforeach</select><x-input-error :messages="$errors->get('status')" class="mt-2" /></div>
    <div><x-input-label for="minimum_amount" :value="__('Minimum Amount')" /><x-text-input id="minimum_amount" name="minimum_amount" type="number" min="0.01" step="0.01" class="mt-1 block w-full" :value="old('minimum_amount', $loanType?->minimum_amount)" required /><x-input-error :messages="$errors->get('minimum_amount')" class="mt-2" /></div>
    <div><x-input-label for="maximum_amount" :value="__('Maximum Amount')" /><x-text-input id="maximum_amount" name="maximum_amount" type="number" min="0.01" step="0.01" class="mt-1 block w-full" :value="old('maximum_amount', $loanType?->maximum_amount)" required /><x-input-error :messages="$errors->get('maximum_amount')" class="mt-2" /></div>
    <div><x-input-label for="minimum_term_months" :value="__('Minimum Term (months)')" /><x-text-input id="minimum_term_months" name="minimum_term_months" type="number" min="1" max="600" class="mt-1 block w-full" :value="old('minimum_term_months', $loanType?->minimum_term_months)" required /><x-input-error :messages="$errors->get('minimum_term_months')" class="mt-2" /></div>
    <div><x-input-label for="maximum_term_months" :value="__('Maximum Term (months)')" /><x-text-input id="maximum_term_months" name="maximum_term_months" type="number" min="1" max="600" class="mt-1 block w-full" :value="old('maximum_term_months', $loanType?->maximum_term_months)" required /><x-input-error :messages="$errors->get('maximum_term_months')" class="mt-2" /></div>
    <div><x-input-label for="annual_interest_rate" :value="__('Annual Interest Rate (%)')" /><x-text-input id="annual_interest_rate" name="annual_interest_rate" type="number" min="0" max="99.99" step="0.01" class="mt-1 block w-full" :value="old('annual_interest_rate', $loanType?->annual_interest_rate)" required /><x-input-error :messages="$errors->get('annual_interest_rate')" class="mt-2" /></div>
    <div><x-input-label for="interest_method" :value="__('Interest Method')" /><select id="interest_method" name="interest_method" class="mt-1 block w-full rounded-lg border-slate-300 bg-white shadow-sm focus:border-emerald-500 focus:ring-emerald-500" required>@foreach ($interestMethods as $method)<option value="{{ $method->value }}" @selected($selectedMethod === $method->value)>{{ $method->label() }}</option>@endforeach</select><x-input-error :messages="$errors->get('interest_method')" class="mt-2" /></div>
    <div><x-input-label for="repayment_frequency" :value="__('Repayment Frequency')" /><select id="repayment_frequency" name="repayment_frequency" class="mt-1 block w-full rounded-lg border-slate-300 bg-white shadow-sm focus:border-emerald-500 focus:ring-emerald-500" required>@foreach ($frequencies as $frequency)<option value="{{ $frequency->value }}" @selected($selectedFrequency === $frequency->value)>{{ $frequency->label() }}</option>@endforeach</select><x-input-error :messages="$errors->get('repayment_frequency')" class="mt-2" /></div>
    <div class="flex items-center gap-3 pt-7"><input id="requires_collateral" name="requires_collateral" type="checkbox" value="1" class="rounded border-slate-300 text-emerald-600 focus:ring-emerald-500" @checked(old('requires_collateral', $loanType?->requires_collateral)) /><x-input-label for="requires_collateral" :value="__('Requires collateral')" /></div>
    <div class="md:col-span-2"><x-input-label for="description" :value="__('Description')" /><textarea id="description" name="description" rows="3" class="mt-1 block w-full rounded-lg border-slate-300 shadow-sm focus:border-emerald-500 focus:ring-emerald-500">{{ old('description', $loanType?->description) }}</textarea><x-input-error :messages="$errors->get('description')" class="mt-2" /></div>
</div>
<div class="mt-6 flex items-center justify-end gap-3"><a href="{{ route('loan-types.index') }}" class="rounded-lg px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">{{ __('Cancel') }}</a><button type="submit" class="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">{{ $submitLabel }}</button></div>
