<x-user.layout :title="__('Two-Factor Authentication')">
    <x-slot:subtitle>
        {{ __('Add extra security to your digital banking account using TOTP mobile authenticator apps.') }}
    </x-slot:subtitle>

    <div class="max-w-2xl mx-auto space-y-6">
        @php
            $is2faEnabled = (bool) $user->two_factor_secret;
        @endphp

        <!-- Main Card -->
        <div class="bg-white rounded-xl border border-slate-200 p-6 space-y-6">
            <!-- Header Status -->
            <div class="flex items-center justify-between pb-4 border-b border-slate-100">
                <div>
                    <h2 class="text-base font-bold text-slate-900">{{ __('Two-Factor Authentication (2FA)') }}</h2>
                    <p class="text-xs text-slate-500 mt-0.5">
                        {{ $is2faEnabled ? __('Your account is secured with time-based one-time passcodes.') : __('Two-factor authentication is currently disabled.') }}
                    </p>
                </div>
                <div>
                    @if($is2faEnabled)
                        <span class="inline-block px-2.5 py-0.5 rounded text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-100">
                            {{ __('Active') }}
                        </span>
                    @else
                        <span class="inline-block px-2.5 py-0.5 rounded text-xs font-semibold bg-slate-100 text-slate-600">
                            {{ __('Disabled') }}
                        </span>
                    @endif
                </div>
            </div>

            @if(!$is2faEnabled)
                <!-- Disabled State -->
                <div class="space-y-4">
                    <p class="text-xs text-slate-600 leading-relaxed">
                        {{ __('When two-factor authentication is enabled, you will be prompted for a secure 6-digit one-time passcode generated by your mobile authenticator app (such as Google Authenticator, Microsoft Authenticator, or 1Password) each time you log in.') }}
                    </p>

                    <form action="{{ route('portal.2fa.enable') }}" method="POST">
                        @csrf
                        <button type="submit"
                                class="px-5 py-2.5 rounded-lg text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white transition">
                            {{ __('Enable Two-Factor Authentication') }}
                        </button>
                    </form>
                </div>
            @else
                <!-- Enabled State -->
                <div class="space-y-6">
                    <!-- QR Code Setup -->
                    <div class="space-y-3">
                        <h3 class="text-xs font-bold text-slate-900 uppercase tracking-wider">{{ __('Scan QR Code') }}</h3>
                        <p class="text-xs text-slate-500">
                            {{ __('Scan this QR code with your mobile authenticator application to connect your banking profile.') }}
                        </p>

                        <div class="p-4 bg-slate-50 rounded-xl border border-slate-200 inline-block">
                            {!! $user->twoFactorQrCodeSvg() !!}
                        </div>
                    </div>

                    <!-- Recovery Codes -->
                    @if($user->two_factor_recovery_codes)
                        <div x-data="{ copied: false }" class="pt-6 border-t border-slate-100 space-y-3">
                            <div class="flex items-center justify-between">
                                <div>
                                    <h3 class="text-xs font-bold text-slate-900 uppercase tracking-wider">{{ __('Emergency Recovery Codes') }}</h3>
                                    <p class="text-xs text-slate-500 mt-0.5">
                                        {{ __('Save these emergency recovery codes in a safe place. You can use them if you lose access to your authenticator device.') }}
                                    </p>
                                </div>
                            </div>

                            <div class="grid grid-cols-2 sm:grid-cols-4 gap-2 p-3 rounded-lg bg-slate-50 border border-slate-200 text-slate-800 font-mono text-xs">
                                @foreach($user->recoveryCodes() as $code)
                                    <div class="py-1 px-2 text-center bg-white rounded border border-slate-200/80">{{ $code }}</div>
                                @endforeach
                            </div>

                            <div class="flex items-center gap-3 pt-1">
                                <form action="{{ route('portal.2fa.recovery-codes') }}" method="POST">
                                    @csrf
                                    <button type="submit" class="text-xs text-emerald-700 hover:underline font-semibold">
                                        {{ __('Regenerate Recovery Codes') }}
                                    </button>
                                </form>
                            </div>
                        </div>
                    @endif

                    <!-- Disable Form -->
                    <div class="pt-6 border-t border-slate-100 flex items-center justify-between">
                        <span class="text-xs text-slate-500">
                            {{ __('Need to change your device or turn off 2FA?') }}
                        </span>
                        <form action="{{ route('portal.2fa.disable') }}" method="POST"
                              onsubmit="return confirm('{{ __('Are you sure you want to disable two-factor authentication?') }}');">
                            @csrf
                            @method('DELETE')
                            <button type="submit"
                                    class="px-4 py-2 rounded-lg text-xs font-semibold text-rose-600 hover:bg-rose-50 border border-rose-200 transition">
                                {{ __('Disable Two-Factor Authentication') }}
                            </button>
                        </form>
                    </div>
                </div>
            @endif
        </div>
    </div>
</x-user.layout>
