@extends('layouts.app')

@section('title', __('Report Details'))

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{ route('reports.index') }}">{{ __('Reports') }}</a></li>
    <li class="breadcrumb-item active">{{ Str::limit($report->title, 30) }}</li>
@endsection

@section('actions')
    @if($report->isCompleted() && $report->file_path)
        <a href="{{ route('reports.download', $report) }}" class="btn btn-primary">
            <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
            </svg>
            <span>{{ __('Download File') }}</span>
        </a>
    @endif
    <a href="{{ route('reports.index') }}" class="btn btn-secondary">
        {{ __('Back to Reports') }}
    </a>
@endsection

@section('content')
<div class="mx-auto max-w-7xl space-y-6 px-4 py-8 sm:px-6 lg:px-8">
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2 space-y-6">
            <div class="bank-card">
                <div class="bank-card-header flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                    <div>
                        <span class="text-xs font-semibold uppercase tracking-wider text-slate-500">{{ $report->report_type->label() }} &bull; {{ $report->format->label() }}</span>
                        <h2 class="text-xl font-bold text-slate-900 mt-0.5">{{ $report->title }}</h2>
                    </div>
                    <span class="inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ring-1 ring-inset {{ $report->status->badgeColor() }}">
                        {{ $report->status->label() }}
                    </span>
                </div>

                <div class="bank-card-body">
                    @if($report->description)
                        <div class="mb-6">
                            <h3 class="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-1.5">{{ __('Description') }}</h3>
                            <p class="text-sm text-slate-700 bg-slate-50 p-3 rounded-lg">{{ $report->description }}</p>
                        </div>
                    @endif

                    <h3 class="text-sm font-semibold text-slate-900 mb-4">{{ __('Report Specifications') }}</h3>
                    <dl class="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-4 text-sm">
                        <div class="flex justify-between border-b border-slate-50 pb-2">
                            <dt class="text-slate-500">{{ __('Type') }}</dt>
                            <dd class="font-medium text-slate-900">{{ $report->report_type->label() }}</dd>
                        </div>
                        <div class="flex justify-between border-b border-slate-50 pb-2">
                            <dt class="text-slate-500">{{ __('Format') }}</dt>
                            <dd class="font-medium text-slate-900 uppercase font-mono" dir="ltr">{{ $report->format->value }}</dd>
                        </div>
                        <div class="flex justify-between border-b border-slate-50 pb-2">
                            <dt class="text-slate-500">{{ __('Branch') }}</dt>
                            <dd class="font-medium text-slate-900">{{ $report->branch?->name ?? __('All Branches') }}</dd>
                        </div>
                        <div class="flex justify-between border-b border-slate-50 pb-2">
                            <dt class="text-slate-500">{{ __('Generated By') }}</dt>
                            <dd class="font-medium text-slate-900">{{ $report->generatedBy?->name ?? __('System') }}</dd>
                        </div>
                        <div class="flex justify-between border-b border-slate-50 pb-2">
                            <dt class="text-slate-500">{{ __('Generated At') }}</dt>
                            <dd class="font-medium text-slate-900 font-mono" dir="ltr">{{ $report->generated_at?->format('Y-m-d H:i') ?? __('Pending') }}</dd>
                        </div>
                        <div class="flex justify-between border-b border-slate-50 pb-2">
                            <dt class="text-slate-500">{{ __('File Size') }}</dt>
                            <dd class="font-medium text-slate-900 font-mono" dir="ltr">{{ $report->file_size ? number_format($report->file_size / 1024, 1) . ' KB' : __('N/A') }}</dd>
                        </div>
                    </dl>
                </div>
            </div>
        </div>

        <div class="space-y-6">
            <div class="bank-card">
                <div class="bank-card-header">
                    <h3 class="text-sm font-semibold text-slate-900">{{ __('Actions & Maintenance') }}</h3>
                </div>
                <div class="bank-card-body space-y-3">
                    <form action="{{ route('reports.generate', $report) }}" method="POST">
                        @csrf
                        <button type="submit" class="w-full btn btn-primary text-xs">
                            <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
                            </svg>
                            <span>{{ __('Regenerate Report') }}</span>
                        </button>
                    </form>

                    <form action="{{ route('reports.destroy', $report) }}" method="POST" onsubmit="return confirm('{{ __('Are you sure you want to delete this report?') }}')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="w-full btn btn-danger text-xs">
                            {{ __('Delete Report') }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
