@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="flex justify-between items-center mb-6">
        <h1 class="text-3xl font-bold text-gray-900">Report Details</h1>
        <a href="{{ route('reports.index') }}" class="text-gray-600 hover:text-gray-900">Back to Reports</a>
    </div>

    @if(session('success'))
        <div class="bg-emerald-100 border border-emerald-400 text-emerald-700 px-4 py-3 rounded mb-4">
            {{ session('success') }}
        </div>
    @endif

    @if(session('error'))
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
            {{ session('error') }}
        </div>
    @endif

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2">
            <div class="bg-white rounded-lg shadow p-6">
                <div class="flex justify-between items-start mb-6">
                    <div>
                        <h2 class="text-xl font-semibold text-gray-900">{{ $report->title }}</h2>
                        <p class="text-sm text-gray-500">{{ $report->report_type->label() }} - {{ $report->format->label() }}</p>
                    </div>
                    @switch($report->status->value)
                        @case('pending')
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">Pending</span>
                            @break
                        @case('generating')
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">Generating</span>
                            @break
                        @case('completed')
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-emerald-100 text-emerald-800">Completed</span>
                            @break
                        @case('failed')
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-red-100 text-red-800">Failed</span>
                            @break
                        @case('scheduled')
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-purple-100 text-purple-800">Scheduled</span>
                            @break
                        @default
                            <span class="px-3 py-1 inline-flex text-sm leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">{{ $report->status->label() }}</span>
                    @endswitch
                </div>

                @if($report->description)
                    <div class="mb-6">
                        <h3 class="text-lg font-semibold text-gray-900 mb-2">Description</h3>
                        <p class="text-gray-700">{{ $report->description }}</p>
                    </div>
                @endif

                <div class="border-t pt-4">
                    <h3 class="text-lg font-semibold text-gray-900 mb-4">Report Information</h3>
                    <dl class="grid grid-cols-1 gap-4">
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Type</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->report_type->label() }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Format</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->format->label() }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Branch</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->branch?->name ?? 'All Branches' }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Generated By</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->generatedBy?->name ?? 'System' }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Created</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->created_at->format('M d, Y H:i:s') }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Generated</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->generated_at?->format('M d, Y H:i:s') ?? 'Not generated' }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Scheduled</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->scheduled_at?->format('M d, Y H:i:s') ?? 'Not scheduled' }}</dd>
                        </div>
                        <div class="flex justify-between">
                            <dt class="text-sm text-gray-500">Expires</dt>
                            <dd class="text-sm font-medium text-gray-900">{{ $report->expires_at?->format('M d, Y H:i:s') ?? 'Never' }}</dd>
                        </div>
                        @if($report->record_count)
                            <div class="flex justify-between">
                                <dt class="text-sm text-gray-500">Record Count</dt>
                                <dd class="text-sm font-medium text-gray-900">{{ number_format($report->record_count) }}</dd>
                            </div>
                        @endif
                        @if($report->file_size)
                            <div class="flex justify-between">
                                <dt class="text-sm text-gray-500">File Size</dt>
                                <dd class="text-sm font-medium text-gray-900">{{ $this->formatFileSize($report->file_size) }}</dd>
                            </div>
                        @endif
                    </dl>
                </div>

                @if($report->error_message)
                    <div class="mt-4 bg-red-50 border border-red-200 rounded-lg p-4">
                        <h3 class="text-sm font-semibold text-red-800">Error Information</h3>
                        <p class="text-sm text-red-700 mt-1">{{ $report->error_message }}</p>
                    </div>
                @endif
            </div>
        </div>

        <div>
            <div class="bg-white rounded-lg shadow p-6 mb-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-4">Actions</h3>
                <div class="space-y-3">
                    @if($report->canBeDownloaded())
                        <a href="{{ route('reports.download', $report) }}" class="block w-full text-center bg-emerald-600 text-white px-4 py-2 rounded-lg hover:bg-emerald-700 text-sm">Download Report</a>
                    @endif

                    @if($report->canBeRegenerated())
                        <form action="{{ route('reports.regenerate', $report) }}" method="POST">
                            @csrf
                            <button type="submit" class="w-full bg-yellow-600 text-white px-4 py-2 rounded-lg hover:bg-yellow-700 text-sm">Regenerate Report</button>
                        </form>
                    @endif

                    @if($report->status === \App\Modules\Reports\Enums\ReportStatus::Scheduled)
                        <div class="bg-blue-50 border border-blue-200 rounded-lg p-3">
                            <p class="text-sm text-blue-800">
                                <strong>Scheduled:</strong> {{ $report->scheduled_at->format('M d, Y H:i') }}
                            </p>
                        </div>
                    @endif
                </div>
            </div>

            @if($report->parameters)
                <div class="bg-white rounded-lg shadow p-6 mb-6">
                    <h3 class="text-lg font-semibold text-gray-900 mb-4">Parameters</h3>
                    <pre class="text-xs text-gray-600 bg-gray-50 p-3 rounded overflow-auto">{{ json_encode($report->parameters, JSON_PRETTY_PRINT) }}</pre>
                </div>
            @endif

            @if($report->metadata)
                <div class="bg-white rounded-lg shadow p-6">
                    <h3 class="text-lg font-semibold text-gray-900 mb-4">Metadata</h3>
                    <pre class="text-xs text-gray-600 bg-gray-50 p-3 rounded overflow-auto">{{ json_encode($report->metadata, JSON_PRETTY_PRINT) }}</pre>
                </div>
            @endif
        </div>
    </div>
</div>

@php
function formatFileSize($bytes) {
    if ($bytes >= 1073741824) {
        return number_format($bytes / 1073741824, 2) . ' GB';
    } elseif ($bytes >= 1048576) {
        return number_format($bytes / 1048576, 2) . ' MB';
    } elseif ($bytes >= 1024) {
        return number_format($bytes / 1024, 2) . ' KB';
    } elseif ($bytes > 1) {
        return $bytes . ' bytes';
    } elseif ($bytes == 1) {
        return '1 byte';
    } else {
        return '0 bytes';
    }
}
@endphp
@endsection
